


num_queries: 100
aux_loss : False
num_labels: 1
class_cost : 1.0
bbox_cost : 5.0
giou_cost : 2.0
eos_coefficient : 0.1
bbox_loss_coefficient : 5
giou_loss_coefficient : 2

FeatureExtractorEncoder:
  Backbone: resnet50
  Pretrained: True
  FreezeLayers: ['layer1', 'layer2', 'layer3']
  OutIndecies: [1,2,3,4]

TransformerEncoder:
  temperature: 10000
  pos_encoding_type : 'sine'
  embedded_dimension: 256
  num_layers: 6
  num_attention_heads: 8
  ffn_dimension: 2048
  dropout_rate: 0.1
  attention_dropout_rate: 0.0
  activation_dropout_rate: 0.0
  layer_dropout_rate: 0.0
  init_std: 0.02
  xavier_std: 1.0

TransformerDecoder:
  embedded_dimension: 256
  num_layers: 6
  num_attention_heads: 8
  ffn_dimension: 2048
  dropout_rate: 0.1
  attention_dropout_rate: 0.0
  activation_dropout_rate: 0.0
  layer_dropout_rate: 0.0
  init_std: 0.02
  xavier_std: 1.0

